services:
  producer-traffic:
    container_name: producer-traffic
    image: producer-traffic
    build: producer-traffic
    env_file:
      - .env
      
  producer-weather:
    container_name: producer-weather
    image: producer-weather
    build: producer-weather
    env_file:
      - .env